### ISSUE TITLE
Does not list the correct topics on a selected channel

### ISSUE THREAD

**Issue by walidkayhan** [lexiconhq/lexicon#2]
Hello, first off just wanted to say this is a very awesome app! I really love the implementation using popular languages and technologies used which are easy to understand and maintain. 

I did notice a few issues with the app when doing some testing with it using our own discourse server and the default one (meta.discource.org). 

# Issue
Whenever you select a channel, there seems to be some strange hiccup when rendering the correct topics that fall under it, that issue might be related to how the useEffect is working in the Home.tsx file to load the relevant topics, but I am not 100% sure:

https://github.com/lexiconhq/lexicon/blob/e0a61d2f535181525edb3c1312aed51976c6ddec/frontend/src/screens/Home/Home.tsx#L339

# Screenshots
These are a couple of screenshots for example, you can see the community channel is selected, but topics with other categories are showing up in the list:

<img src="https://user-images.githubusercontent.com/45078505/136048613-bab110c9-e69d-487f-986c-5cc9ae48559b.png" width="350" /> <img src="https://user-images.githubusercontent.com/45078505/136048668-7e5c4b9a-ed4c-4cb3-b0cc-bf924c9d7b1a.png" width="350" />

**Comment by Kinostrome** [comment]
I'll close this for now, but feel free to comment / re-open if you're still running into it.

**Comment by Joshagos** [comment]
> Hey @walidkayhan, thanks for your kind words—it means a lot! I also appreciate you taking the time to contribute to Lexicon.
> 
> Sorry for the delayed response here.
> 
> And doubly sorry because we had actually fixed this shortly after launching, and hadn't yet pushed it. This was a bug I was well aware of, and it was personally driving me nuts for quite a while. So I was glad to finally have it resolved.
> 
> I've just pushed some changes that include the fix for this issue. So if you pull down the latest from `master`, you should no longer see that occurring.

Where have you guys been for so long? What happened? Will you leave us again?
