### ISSUE TITLE
Update Lexicon to move to the new Apollo Router from @apollo/gateway

### ISSUE THREAD

**Issue by bilalghalib** [lexiconhq/lexicon#21]
in order to upgrade react and expo we need to update Apollo like described here:
https://www.apollographql.com/docs/router/migrating-from-gateway/

**Comment by Kinostrome** [comment]
Thanks for filing this—added to the roadmap.

**Comment by Kinostrome** [comment]
Closing this as we've already upgraded React and Expo.
