### ISSUE TITLE
"Something went wrong" Failed to setup push notifications

### ISSUE THREAD

**Issue by biohackinginternational** [lexiconhq/lexicon#60]
### *REQUIRED:* Include the contents of `api/.env` and `frontend/.env`
_If you are manually overriding any environment variables when running the package scripts, include those as well._

**api/.env**
```
PROSE_DISCOURSE_HOST=https://forum.biohackinginternational.com
```

**frontend/.env**
```
No content
```

### _REQUIRED:_ answer the following questions:
- If this is related to your mobile app:
  - Are you running it through Expo, or did you build it? **Built It**
  - Is it running on your mobile device or on a simulator?
 **Mobile Device**

### To Reproduce
1. Go to Testflight
2. Click on Install
3. Click on open
4. Login to account
5. On prompt "Biohacking Community" would like to send you notifications, click allow
6. Error popup: Something went wrong failed to setup push notifications

### Expected behavior
Upon clicking allow, no error popups up and push notifications work as intended

### Screenshots
![image](https://github.com/lexiconhq/lexicon/assets/141676979/b2344ce7-2a3d-4016-97ea-365659da6564)

#### Desktop (please complete the following information):
 - OS: [e.g. iOS] iOS

#### Smartphone (please complete the following information):
 - Device: [e.g. iPhone6] iPhone 11 Pro Max

#### GraphQL API (please complete the following information):
Please indicate where the Prose GraphQL API is running.
https://prose.biohackinginternational.com 

Are you only running it locally on your development machine?
Production app

Have you deployed it somewhere? If so, what domain or IP address did you deploy it at?
No, I used the expo build website and expo-cli to build the app then added it to apple transporter and into test flight.

How specifically did you configure the mobile app to connect to the API?
Set all proseUrl to https://prose.biohackinginternational.com in the config.ts

**Comment by starjustice** [comment]
Hi @biohackinginternational, thank you for bringing this issue to our attention. To better assist you, could you please provide additional information? 
Have you already added `currentFullName` to the app.json file

**Comment by biohackinginternational** [comment]
Thank you for helping me to look into this!!! 

This is the value for currentFullName: "currentFullName": "@<username>/<slugName>",

Thanks!

**Comment by biohackinginternational** [comment]
> Hi @biohackinginternational, thank you for bringing this issue to our attention. To better assist you, could you please provide additional information? Have you already added `currentFullName` to the app.json file

Thank you for helping me to look into this!!! 

This is the value for currentFullName: ```"currentFullName": "@<username>/<slugName>",```

Thanks!

**Comment by biohackinginternational** [comment]
> Hi @biohackinginternational, thank you for bringing this issue to our attention. To better assist you, could you please provide additional information? Have you already added `currentFullName` to the app.json file

Is there a specific value it should have instead of the value above?

**Comment by starjustice** [comment]
> > Hi @biohackinginternational, thank you for bringing this issue to our attention. To better assist you, could you please provide additional information? Have you already added `currentFullName` to the app.json file
> 
> Is there a specific value it should have instead of the value above?

Hey @biohackinginternational, After we checked, there is a missing regex check for "experienced," which makes `@<username>/<slugName>` not valid. To solve this, you can change the value to `@username/<slugName>`.

**Comment by biohackinginternational** [comment]
> > > Hi @biohackinginternational, thank you for bringing this issue to our attention. To better assist you, could you please provide additional information? Have you already added `currentFullName` to the app.json file
> > 
> > 
> > Is there a specific value it should have instead of the value above?
> 
> Hey @biohackinginternational, After we checked, there is a missing regex check for "experienced," which makes `@<username>/<slugName>` not valid. To solve this, you can change the value to `@username/<slugName>`.

Gotcha do I need to put a specific value for @username?

**Comment by starjustice** [comment]
> > > > Hi @biohackinginternational, thank you for bringing this issue to our attention. To better assist you, could you please provide additional information? Have you already added `currentFullName` to the app.json file
> > > 
> > > 
> > > Is there a specific value it should have instead of the value above?
> > 
> > 
> > Hey @biohackinginternational, After we checked, there is a missing regex check for "experienced," which makes `@<username>/<slugName>` not valid. To solve this, you can change the value to `@username/<slugName>`.
> 
> Gotcha do I need to put a specific value for @username?

No. But the username value here is the username for the expo account which will used for building the app.

**Comment by biohackinginternational** [comment]
Will let you know if its solved in a few!

**Comment by biohackinginternational** [comment]
IT WORKS! Thank you :)
