### ISSUE TITLE
[about] Cannot return null for non-nullable field About.topicCount.

### ISSUE THREAD

**Issue by biohackinginternational** [lexiconhq/lexicon#61]
### Describe the bug
When using the application and clicking "Latest" or "Top"(only those), a new line shows in the output of the prose instance saying "[about] Cannot return null for non-nullable field About.topicCount."

### *REQUIRED:* Include the contents of `api/.env` and `frontend/.env`
_If you are manually overriding any environment variables when running the package scripts, include those as well._

**api/.env**
```
PROSE_DISCOURSE_HOST=https://forum.biohackinginternational.com
```

**frontend/.env**
```
No content
```

### _REQUIRED:_ answer the following questions:
- If this is related to your mobile app:
  - Are you running it through Expo, or did you build it? Built it
  - Is it running on your mobile device or on a simulator? Mobile Device, Same issue in simulator

### To Reproduce
1. Go to testflight
2. Click on install
3. Click on open
4. Tap "Latest" or "Top"
5. "[about] Cannot return null for non-nullable field About.topicCount." pops up in the output of the prose

### Expected behavior
Upon clicking "Latest" or "Top" nothing should appear in the console.

### Screenshots
<img width="1254" alt="Screenshot 2023-12-09 at 1 17 58 PM" src="https://github.com/lexiconhq/lexicon/assets/141676979/2c967a55-12ed-4c9c-bc59-e504a037ec2e">

#### Desktop (please complete the following information):
 - OS: [e.g. iOS] iOS
 - Version [e.g. 22] 17.0

#### GraphQL API (please complete the following information):
Please indicate where the Prose GraphQL API is running.

https://prose.biohackinginternational.com

Are you only running it locally on your development machine? Production

Have you deployed it somewhere? If so, what domain or IP address did you deploy it at? https://prose.biohackinginternational.com

How specifically did you configure the mobile app to connect to the API? Set proseUrl for everything in frontend/Config.ts to https://prose.biohackinginternational.com

### Additional context
All the content and stuff shows but still has those output in the logs, is this possibly tied with the notification issue?

**Comment by starjustice** [comment]
Hey @biohackinginternational, thanks for reporting this bug. The fix for this issue will be included in the next release. However, if you'd like to try fixing it yourself, you can navigate to the file `api/src/resolvers/site/aboutQuery.ts`.

Modify the code on line 14 to the following:
```
    let {
      data: {
        about: {
          stats: {
            topics_count: topicsCount,
            topic_count: topicCount,
            posts_count: postsCount,
            post_count: postCount,
          },
        },
      },
    } = await context.client.get(siteUrl);

    return {
      topicCount: topicCount || topicsCount,
      postCount: postCount || postsCount,
    };
```

**Comment by Kinostrome** [comment]
Hey @biohackinginternational, since it has been several months since we have heard from you about this issue, we will soon close it as resolved.

Please let us know if you have further questions.

**Comment by Kinostrome** [comment]
Closing this since we never heard back, and the issue should already be fixed in the latest release.
